FROM node:20-alpine

WORKDIR /app

# Copiar manifiestos
COPY apps/frontend/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar código fuente
COPY apps/frontend/ ./

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host"]
